@startuml
skinparam classAttributeIconSize 0
hide circle

!theme plain
top to bottom direction
skinparam linetype ortho

class Chrono {

}

class Subject {

}

class Observer {
    +update()
}
Subject <|-- Chrono
@enduml
