@startuml
skinparam classAttributeIconSize 0
hide circle

!theme plain
top to bottom direction
skinparam linetype ortho

class Subject {
    +attach()
    +detach()
    +notifyObservers()
}

class Observer {
    +update()
}

class ChronoManager {
    - nbChronos: int
}

class DialManager {

}

class Chrono {
    -timer: Timer
    +getTimer(): Timer
}

class Dial {
    +update()
}

Subject <|-- Chrono
Observer <|-- Dial
Subject -> Observer: observers
Chrono <- Dial: chrono
ChronoManager o-- Chrono: chronos
DialManager o-- Dial: dials
ChronoManager -right[hidden]- Subject
DialManager -left[hidden]- Observer
@enduml
